### ISSUE TITLE
What does your dev environment look like? Hardware  + Software

### ISSUE THREAD

**Issue by AchoArnold** [woliveiras/ama#2]

**Comment by woliveiras** [comment]
Hello @AchoArnold! 

I like to mount this PC:

**Hardware**:

* Intel Core i7
* 8 GB of memory
* SSD (180 GB is just what i need)

But my realy is:

* Intel Core i3
* 4 GB of memory
* HD 500GB with 7200 RPM

And is in a old PC! kkkkkkk

**Software**:

* SO: Ubuntu
* Browsers: Chrome (i love the dev tools! ;D) and Firefox
* Virtualization: Docker
* IDE/Text Editor: Sublimetext with [this](https://github.com/woliveiras/dotfiles/tree/master/sublimetext) configurations and i'm in migrating now to VIM with [this](https://github.com/woliveiras/dotfiles/blob/master/.vimrc) configs. I dont use IDE because use lint and hint plugins in Sublime and tasks to test my code in Gulpjs.
* Others: Nodejs, Gulpjs, Bower, NPM and Yeoman

**Comment by AchoArnold** [comment]
Thanks
